spring:
  profiles:
    active: "dev"
  jpa:
    openInView: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
#        cache:
#          use_query_cache: true
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
#        javax:
#          cache:
#            provider: org.ehcache.jsr107.EhcacheCachingProvider
#            uri: classpath:ehcache.xml 
  hateoas:
    use-hal-as-default-json-media-type: false
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
server:
  port: 5000
  servlet:
    contextPath: /dashboard
---
spring:
  profiles: dev
#  datasource:
#    url: jdbc:oracle:thin:@kesar.com:8888:SIDDEV
#    username: kesar
#    password: test12345
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 5
logging:
  config: classpath:log4j2.xml
---
spring:
  profiles: uat  
---
spring:
  profiles: prd, cob
